stars: # a list of possible reactions
  - â­
  - ðŸ’«
  - ðŸŒŸ

# the threshold for a message to be posted in the starboard (# of stars > threshold)
threshold: 1

# ID of the guild (server) the starboard is on
guild: 290573725366091787

# ID of the starboard channel
starboard: 319830765842071563

# name of a file with only the bot's token inside
token_file: "token.txt"
